services:
  postgres:
    container_name: postgre-sql
    image: postgres
    environment:
      POSTGRES_USER: majornick
      POSTGRES_PASSWORD: majornick
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped


networks:
  microservices-net:
    driver: bridge
volumes:
  postgres:

